before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths: [vendor/*, app/*, web/*]

tools:
    php_cpd: true
    php_code_coverage: true
    php_code_sniffer: true
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend:
        excluded_dirs: [vendor]
